server.port=${PORT:2020}
spring.application.name=${APPLICATION_NAME:RENTDI-APP}
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:RentDiApp}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret=${JWT_SECRET:rentdi_secret_key_for_jwt_token_signing_please_change_in_production}
jwt.expiration=86400000
jwt.refresh.expiration=2592000000